## Preprocessing

In [38]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [39]:
# Drop the non-beneficial ID columns, 'EIN'
#  YOUR CODE GOES HERE
application_df = application_df.drop(["EIN"], 1)
application_df.head()

<ipython-input-39-556d4ac10ae4>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  application_df = application_df.drop(["EIN"], 1)

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [43]:
name_counts = application_df["NAME"].value_counts()
name_counts[name_counts>5]

PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
OLD OAK CLIFF CONSERVATION LEAGUE INC                 6
AMERICAN NEPHROLOGY NURSES ASSOCIATION                6
HUMBLE ISD EDUCATIONAL SUPPORT GROUPS INC             6
PROFESSIONAL LOADMASTER ASSOCIATION                   6
CBMC INC                                              6
Name: NAME, Length: 354, dtype: int64

In [45]:
names_to_replace = list(name_counts[name_counts <= 5].index)
for app in names_to_replace:
  application_df["NAME"] = application_df["NAME"].replace(app, "Other")
application_df["NAME"].value_counts()

Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: NAME, Length: 355, dtype: int64

In [44]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [46]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
application_counts = application_df["APPLICATION_TYPE"].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [47]:
application_counts[application_counts < 500].index

Index(['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17'], dtype='object')

In [48]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace= list(application_counts[application_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [23]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
class_counts = application_df["CLASSIFICATION"].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [24]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [25]:
class_counts[class_counts > 10]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
Name: CLASSIFICATION, dtype: int64

In [26]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(class_counts[class_counts < 1000].index)


# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [27]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_with_dummies_df = pd.get_dummies(application_df)
application_with_dummies_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [52]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
X = application_with_dummies_df.drop(["IS_SUCCESSFUL"], axis="columns").values
y = application_with_dummies_df["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [53]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [54]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_feature = len(X_train[0])
hidden_nodes_layers1 = 100
hidden_nodes_layers2 = 30
hidden_nodes_layers3 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers1, input_dim=number_input_feature, activation="relu")
)


# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers2,  activation="sigmoid")
)

nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers3,  activation="sigmoid")
)


# Output layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=1,  activation="sigmoid")
)


# Check the structure of the model
nn.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_19 (Dense)            (None, 100)               4400

 dense_20 (Dense)            (None, 30)                3030

 dense_21 (Dense)            (None, 10)                310

 dense_22 (Dense)            (None, 1)                 11

=================================================================
Total params: 7751 (30.28 KB)
Trainable params: 7751 (30.28 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [55]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [56]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs = 100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5827 - accuracy: 0.7187
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5591 - accuracy: 0.7311
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5550 - accuracy: 0.7310
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5525 - accuracy: 0.7324
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5511 - accuracy: 0.7325
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7335
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7329
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7348
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7339
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5471 - accuracy: 0.7355
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7350
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7357
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7356
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7358
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7358
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7364
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7360
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5434 - accuracy: 0.7368
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7374
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7365
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7371
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7373
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7374
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7377
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5417 - accuracy: 0.7380
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5413 - accuracy: 0.7372
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7379
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7383
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7386
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7388
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7378
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7375
Epoch 33/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5400 - accuracy: 0.7383
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7384
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7388
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7385
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7385
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7393
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7395
Epoch 40/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5386 - accuracy: 0.7390
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7393
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7386
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7394
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7396
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7399
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7392
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5375 - accuracy: 0.7401
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7397
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7399
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7399
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7399
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7398
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7399
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7397
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5367 - accuracy: 0.7404
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7399
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7404
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7404
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7397
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7404
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7411
Epoch 62/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5361 - accuracy: 0.7413
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7409
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7406
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7408
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7411
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7402
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7404
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7413
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7408
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7405
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7405
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7411
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7405
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7414
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5348 - accuracy: 0.7413
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5350 - accuracy: 0.7407
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7411
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7411
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7407
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7415
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7413
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7415
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7416
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7421
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7416
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7411
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7416
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7409
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7407
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7419
Epoch 92/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5339 - accuracy: 0.7414
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7409
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7413
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7416
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7416
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7416
Epoch 98/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5339 - accuracy: 0.7411
Epoch 99/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5337 - accuracy: 0.7417
Epoch 100/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5343 - accuracy: 0.7417

In [57]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5537 - accuracy: 0.7251 - 551ms/epoch - 2ms/step
Loss: 0.5537233352661133, Accuracy: 0.7251312136650085

In [58]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


# Overview of the analysis: Explain the purpose of this analysis.

# Results: Using bulleted lists and images to support your answers, address the following questions:

# Data Preprocessing

1. What variable(s) are the target(s) for your model?
  **Answer** The Target is the IS-Successful column

2. What variable(s) are the features for your model?

**Answer** Features list of this model are the following name, application type afflication classification use_case organization income special considerations status and ask amount

3. What variable(s) should be removed from the input data because they are neither targets nor features?
**Answer** EIN (employee identification)

# Compiling, Training, and Evaluating the Model

1. How many neurons, layers, and activation functions did you select for your neural network model, and why?

**Answer** For this model 3 hidden layers each with many neurons because the compute seems to increate the accuracy above 75% This is expensive and costly. The first activiations is relu and the other layers are sigmoid it might boost accuracy using the functions. Readjusting my data that names as a get dummies can factor in with better scores.

2. Were you able to achieve the target model performance?
Yes
3. What steps did you take in your attempts to increase model performance?
Required to convert the NAME into data points which has the biggest impact on improbing efficiency but costly and it requires adding third layer using sigmoid activision function

# Summary: Summarize the overall results of the deep learning model.

Overall the accuracy above 75% we are able to correctly classify each in the test 75% of the time.
And an application has a 80% chance of being successful if they following:

Name of applicats appears more than 5 times
type of applications following T3 T4 T5 T6 T7 T8  T10 T19
application of following classification ...



# Include a recommendation for how a different model could solve this classification problem
# and then explain your recommendation.

RandomForest model

In [59]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [60]:
rf_model = RandomForestClassifier(n_estimators= 120, random_state=78)

rf_model = rf_model.fit(X_train_scaled, y_train)

y_pred = rf_model.predict(X_test_scaled)

print(f"Random Forest model accuracy {accuracy_score(y_test, y_pred)}")

Random Forest model accuracy 0.7100874635568513